# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sourse\main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_count_buyers = QtWidgets.QLabel(self.centralwidget)
        self.label_count_buyers.setGeometry(QtCore.QRect(20, 20, 111, 16))
        self.label_count_buyers.setObjectName("label_count_buyers")
        self.label_count_goods = QtWidgets.QLabel(self.centralwidget)
        self.label_count_goods.setGeometry(QtCore.QRect(180, 50, 111, 16))
        self.label_count_goods.setObjectName("label_count_goods")
        self.label_count_products = QtWidgets.QLabel(self.centralwidget)
        self.label_count_products.setGeometry(QtCore.QRect(130, 20, 111, 16))
        self.label_count_products.setObjectName("label_count_products")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_count_buyers.setText(_translate("MainWindow", "Покупателей: 0"))
        self.label_count_goods.setText(_translate("MainWindow", "Товаров: 0"))
        self.label_count_products.setText(_translate("MainWindow", "Товаров: 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
